### PR TITLE
Updates to the text.

### PR DESCRIPTION
**Pull request by Lauragra**

### CODE REVIEW

**Comment by mikewheaton** [comment]
Thanks so much for these edits, @Lauragra! Approved by me. @Eclair, take a look and see if we're okay to merge these in?

**Comment by Eclair** [comment]
Hi @Lauragra , thanks you so much for these changes! Everything looks great except for link to "license" file, our license file has no .md format, it's just "LICENSE" in the root directory, could you please change the link to file in License section of readme? everything else looks great!

**Comment by Lauragra** [comment]
Removed the link. Thanks!

**Comment by Eclair** [comment]
Looks great!

**Pull request merged**
